# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA_PROJECTS/audio_visualiser/audio_visualiser.cache/wt [current_project]
set_property parent.project_path D:/FPGA_PROJECTS/audio_visualiser/audio_visualiser.xpr [current_project]
set_property XPM_LIBRARIES XPM_FIFO [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/FPGA_PROJECTS/audio_visualiser/audio_visualiser.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/Oled_Display.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/audio_fifo_bridge.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/audio_input_pipeline.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/audio_output_pipeline.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/audio_peak_detector.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/clock_divider.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/dac_controller.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/dc_block_hp.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/display_frame_smoother.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/display_pipeline.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/fft_processor.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/frequency_band_filter.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/level_0_999.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/mic_sample_clock.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/mic_spi_capture.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/oled_graphics_engine.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/pcm16_to_u12.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/sample_buffer_ram.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/sample_frame_packer.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/seg_scan4.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/seven_segment.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/soft_gain_ramp.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/spi16_dual_da2.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/stream_to_array.v
  C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/sources_1/new/top.v
}
read_ip -quiet d:/FPGA_PROJECTS/audio_visualiser/audio_visualiser.srcs/sources_1/ip/xfft_0/xfft_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA_PROJECTS/audio_visualiser/audio_visualiser.srcs/sources_1/ip/xfft_0/xfft_0_ooc.xdc]

read_ip -quiet d:/FPGA_PROJECTS/audio_visualiser/audio_visualiser.srcs/sources_1/ip/xfft_1/xfft_1.xci
set_property used_in_implementation false [get_files -all d:/FPGA_PROJECTS/audio_visualiser/audio_visualiser.srcs/sources_1/ip/xfft_1/xfft_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/constrs_1/new/basys3_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/siddh/AppData/Local/Temp/18e9697a-e410-41bd-bcb0-c47dba33b903_fpga_audio_visualiser--edit.zip.903/fpga_audio_visualiser--edit/fpga_audio_visualiser/fpga_audio_visualiser.srcs/constrs_1/new/basys3_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
