# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/basys3_constraints.xdc

# IP: ip/xfft_1/xfft_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xfft_1 || ORIG_REF_NAME==xfft_1} -quiet] -quiet

# IP: ip/xfft_0/xfft_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet
